import type { Metadata } from "next";
import { Inter, Roboto_Mono } from 'next/font/google';
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger
} from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import "../globals.css";

const inter = Inter({
  subsets: ['latin'],
  // Optional: Configure font display and other options
  display: 'swap',
  // Optional: Specify weight if you don't need all weights
  weight: ['400', '500', '600', '700'],
});

const Roboto = Roboto_Mono({
  subsets: ['latin'],
  // Optional: Configure font display and other options
  display: 'swap',
  // Optional: Specify weight if you don't need all weights
  weight: ['400']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider defaultOpen>
          <AppSidebar />
          <SidebarInset>
            <header className={`${inter.className} ${Roboto.variable} lex h-16 items-center gap-4 border-b px-6antialiased`}>
              <SidebarTrigger />
            </header>
            {children}
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
