import type React from 'react';
import type { Metadata } from 'next';
import { Inter, Roboto_Mono } from 'next/font/google';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { TopNav } from '@/components/top-nav';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700']
});

const Roboto = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${Roboto.variable}`}>
        <SidebarProvider defaultOpen>
          <div className="relative flex min-h-screen flex-col">
            <TopNav />
            <div className="flex flex-1 pt-16">
              {' '}
              {/* Add pt-16 to create space for the fixed top nav */}
              <AppSidebar />
              <SidebarInset>
                <main className="flex-1 overflow-y-auto">
                  <div className="container mx-auto px-4 py-6 md:px-6">
                    {children}
                  </div>
                </main>
              </SidebarInset>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
