import type { Metadata } from "next";
import { Inter, Roboto_Mono } from 'next/font/google';
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  // Optional: Configure font display and other options
  display: 'swap',
  // Optional: Specify weight if you don't need all weights
  weight: ['400', '500', '600', '700'],
});

const Roboto = Roboto_Mono({
  subsets: ['latin'],
  // Optional: Configure font display and other options
  display: 'swap',
  // Optional: Specify weight if you don't need all weights
  weight: ['400']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${Roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
