import type React from 'react';
import type { Metadata } from 'next';
import { Inter, Roboto_Mono } from 'next/font/google';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { TopNav } from '@/components/top-nav';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700']
});

const Roboto = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${Roboto.variable}`}>
        <SidebarProvider defaultOpen>
          <TopNav />
          <div className="flex pt-16">
            <AppSidebar />
            <SidebarInset>
              <main className="w-full">
                <div className="mx-auto w-full max-w-7xl px-4 py-6 md:px-6 lg:px-8">
                  {children}
                </div>
              </main>
            </SidebarInset>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
